### PR TITLE
Improve everything

### PR DESCRIPTION
**Pull request by Stilic**
PLEASE DONT MERGE, ITS STILL A WIP!!!!

Also, @magnumsrtisswag, could you please remove these tags from the GitHub repository?
image

### CODE REVIEW

**Comment by TheKitBoi** [comment]
Why would you remove the haxelib install hscript text on workflows cus it’s in the Project.xml 
Unless there is a reason you removed it

**Comment by Stilic** [comment]
@magnumsrtisswag @TheKitBoi This pull request is now ready to be merged! (Make sure to test it before)

**Comment by Stilic** [comment]
ok please wait until i fix two things

**Comment by Stilic** [comment]
OK NOW ITS REALLY READY MEN!

**Comment by magnumsrtisswag** [comment]
Alright dude, I'm not trying to be rude, but a LOT of the stuff here is from psych, you can't just yoink that many variables and say your "fixing" the dad animations by just stealing the sprite sheet from psych engine. I understand you wanna help, but you can't take that many lines of code from psych engine and expect me to approve of that. I'm gonna close this, I'm not gonna like block you or anything. But PLEASE, don't do this again.

**Comment by magnumsrtisswag** [comment]
I said I would merge, but I had no idea that the code was mostly shadow mario's.

**Comment by Stilic** [comment]
Ok, I will try to reduce code taken from psych so.

**Pull request closed without merging**
